<?php

/**
 * @file
 * Contains bigbox_payment_state.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bigbox_payment_state_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bigbox_payment_state module.
    case 'help.page.bigbox_payment_state':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Модуль выводит состояние оплаты на dashboard, меняет состояние оплаты, блокирует сайт.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function bigbox_payment_state_install()
{
  \Drupal::state()->set('bigbox_trial', TRUE);
  \Drupal::state()->set('bigbox_time_close_site', time() + (int) \Drupal::config('bigbox_payment_state.settings')->get('trial_days') * 24 * 60 * 60);
  \Drupal::state()->set('bigbox_site_active', TRUE);
  \Drupal::state()->set('bigbox_alert_visible', TRUE);
}

/**
 *  Close the site if the payment time has expired.
 *
 * Implements hook_cron().
 */
function bigbox_payment_state_cron()
{
  if ((time() > \Drupal::state()->get('bigbox_time_close_site')) && \Drupal::state()->get('bigbox_site_active')) {
    \Drupal::state()->set('bigbox_site_active', FALSE);
    \Drupal::state()->set('bigbox_alert_visible', TRUE);
  }
}

/**
 * Implements hook_theme().
 */
function bigbox_payment_state_theme($existing, $type, $theme, $path)
{
  return [
    'alert_site_status' => [
      'variables' => ['vars' => NULL],
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bigbox_payment_state_preprocess_page__front(&$variables)
{
  $plugin_block = \Drupal::service('plugin.manager.block')->createInstance('alert_site_status', []);
  $build = $plugin_block->build();
  $variables['page']['content']['alert_site_status'] = $build ;
}




